list_of_surah = {
    1 : {"ar": "Al Fatihah ", "id": "Pembukaan"},
    2 : {"ar": "Al Baqarah ", "id": "Sapi Betina"},
    3 : {"ar": "Ali 'Imran ", "id": "Keluarga 'Imran"},
    4 : {"ar": "An Nisa' ", "id": "Wanita"},
    5 : {"ar": "Al Ma'idah ", "id": "Hidangan"},
    6 : {"ar": "Al An'am ", "id": "Binatang Ternak"},
    7 : {"ar": "Al A'raf  ", "id": "Tempat Tertinggi"},
    8 : {"ar": "Al Anfal ", "id": "Rampasan Perang"},
    9 : {"ar": "At Taubah ", "id": "Pengampunan"},
    10 : {"ar": "Yunus ", "id": "Nabi Yunus A.S."},
    11 : {"ar": "Hud ", "id": "Nabi Huud A.S."},
    12 : {"ar": "Yusuf ", "id": "Nabi Yusuf A.S."},
    13 : {"ar": "Ar Ra'd ", "id": "Guruh"},
    14 : {"ar": "Ibrahim ", "id": "Nabi Ibrahim A.S."},
    15 : {"ar": "Al Hijr ", "id": "Daerah Pegunungan"},
    16 : {"ar": "An Nahl ", "id": "Lebah"},
    17 : {"ar": "Al Israa' ", "id": "Memperjalankan Di Malam Hari"},
    18 : {"ar": "Al Kahfi ", "id": "Gua"},
    19 : {"ar": "Maryam ", "id": "Maryam"},
    20 : {"ar": "Thaha ", "id": "Thaahaa"},
    21 : {"ar": "Al Anbiya' ", "id": "Kisah Para Nabi"},
    22 : {"ar": "Al Hajj ", "id": "Ibadah Haji"},
    23 : {"ar": "Al Mu'minun ", "id": "Orang Mukmin"},
    24 : {"ar": "An Nur ", "id": "Cahaya"},
    25 : {"ar": "Al Furqaan ", "id": "Pembeda"},
    26 : {"ar": "Asy Syu'ara' ", "id": "Penyair"},
    27 : {"ar": "An Naml ", "id": "Semut"},
    28 : {"ar": "Al Qashash ", "id": "Cerita"},
    29 : {"ar": "Al 'Ankabuut ", "id": "Laba-Laba"},
    30 : {"ar": "Ar Ruum ", "id": "Bangsa Rumawi"},
    31 : {"ar": "Luqman ", "id": "Luqman"},
    32 : {"ar": "As Sajdah ", "id": "", "id": "Sujud"},
    33 : {"ar": "Al Ahzab ", "id": "Golongan Yang Bersekutu"},
    34 : {"ar": "Saba' ", "id": "Kaum Saba'"},
    35 : {"ar": "Fathir ", "id": "Pencipta"},
    36 : {"ar":"Yaasiin", "id":"Yasin"},
    37 : {"ar": "Ash Shaffat ", "id": "Yang Bershaf-Shaf"},
    38 : {"ar": "Shaad", "id":"Shaad"},
    39 : {"ar": "Az Zumar ", "id": "Rombongan-Rombongan"},
    40 : {"ar": "Al Mu'min ", "id": "Orang Yang Beriman"},
    41 : {"ar": "Fushshilat ", "id": "Yang Dijelaskan"},
    42 : {"ar": "Asy Syuura ", "id": "Musyawarah"},
    43 : {"ar": "Az Zukhruf ", "id": "Perhiasan"},
    44 : {"ar": "Ad Dukhaan ", "id": "Kabut"},
    45 : {"ar": "Al Jaatsiyah ", "id": "Yang Berlutut"},
    46 : {"ar": "Al Ahqaaf ", "id": "Bukit Pasir"},
    47 : {"ar": "Muhammad ", "id": "Nabi Muhammad SAW"},
    48 : {"ar": "Al Fath ", "id": "Kemenangan"},
    49 : {"ar": "Al Hujuraat ", "id": "Kamar-Kamar"},
    50 : {"ar": "Qaaf", "id": "Qaaf"},
    51 : {"ar": "Adz Dzaariyaat ", "id": "Angin Yang Menerbangkan"},
    52 : {"ar": "Ath Thuur ", "id": "Bukit"},
    53 : {"ar": "An Najm ", "id": "Bintang"},
    54 : {"ar": "Al Qamar ", "id": "Bulan"},
    55 : {"ar": "Ar Rahmaan ", "id": "Yang Maha Pemurah"},
    56 : {"ar": "Al Waaqi'ah ", "id": "Hari Kiamat"},
    57 : {"ar": "Al Hadid ", "id": "Besi"},
    58 : {"ar": "Al Mujadilah ", "id": "Wanita Yang Mengajukan Gugatan"},
    59 : {"ar": "Al Hasyr ", "id": "Pengusiran"},
    60 : {"ar": "Al Mumtahanah ", "id": "Wanita Yang Diuji"},
    61 : {"ar": "Ash Shaff ", "id": "Barisan"},
    62 : {"ar": "Al Jumu'ah ", "id": "Hari Jum'at"},
    63 : {"ar": "Al-Munafiqun ", "id": "Orang-Orang Munafik"},
    64 : {"ar": "At Taghabun ", "id": "Hari Ditampakkan Kesalahan-Kesalahan"},
    65 : {"ar": "Ath Thalaaq ", "id": "Talak"},
    66 : {"ar": "At Tahrim ", "id": "Mengharamkan"},
    67 : {"ar": "Al Mulk ", "id": "Kerajaan"},
    68 : {"ar": "Al Qalam ", "id": "Pena"},
    69 : {"ar": "Al Haqqah ", "id": "Kiamat"},
    70 : {"ar": "Al Ma'arij ", "id": "Tempat-Tempat Naik"},
    71 : {"ar": "Nuh ", "id": "Nabi Nuh A.S"},
    72 : {"ar": "Al Jin ", "id": "Jin"},
    73 : {"ar": "Al Muzzammil ", "id": "Orang Yang Berselimut"},
    74 : {"ar": "Al Muddatstsir ", "id": "Orang Yang Berselimut"},
    75 : {"ar": "Al Qiyamah ", "id": "Hari Kiamat"},
    76 : {"ar": "Al Insaan ", "id": "Manusia"},
    77 : {"ar": "Al Mursalat ", "id": "Malaikat-Malaikat Yang Diutus"},
    78 : {"ar": "An Naba´ ", "id": "Berita Besar"},
    79 : {"ar": "An Naazi´ ", "id": "Malaikat-Malaikat Yang Mencabut"},
    80 : {"ar": "'Abasa ", "id": "Bermuka Masam"},
    81 : {"ar": "At Takwir ", "id": "Menggulung"},
    82 : {"ar": "Al Infithar ", "id": "Terbelah"},
    83 : {"ar": "Al Muthaffifiin ", "id": "Orang-Orang Yang Curang"},
    84 : {"ar": "Al Insyiqaaq ", "id": "Terbelah"},
    85 : {"ar": "Al Buruuj ", "id": "Gugusan Bintang"},
    86 : {"ar": "Ath Thaariq ", "id": "Yang Datang Di Malam Hari"},
    87 : {"ar": "Al A´Laa ", "id": "Yang Paling Tinggi"},
    88 : {"ar": "Al Ghaasyiyah ", "id": "Hari Kiamat"},
    89 : {"ar": "Al Fajr ", "id": "Fajar"},
    90 : {"ar": "Al Balad ", "id": "Negeri"},
    91 : {"ar": "Asy Syams ", "id": "Matahari"},
    92 : {"ar": "Al Lail ", "id": "Malam"},
    93 : {"ar": "Adh Dhuhaa ", "id": "Waktu Dhuha"},
    94 : {"ar": "Alam Nasyrah /Al Insyirah ", "id": "Bukankah Kami Telah Melapangkan"},
    95 : {"ar": "At Tiin ", "id": "Buah Tin"},
    96 : {"ar": "Al 'Alaq ", "id": "Segumpal Darah"},
    97 : {"ar": "Al Qadr ", "id": "Kemuliaan"},
    98 : {"ar": "Al Bayyinah ", "id": "Bukti Yang Nyata"},
    99 : {"ar": "Al Zalzalah ", "id": "Goncangan"},
    100 : {"ar": "Al 'Adiyat ", "id": "Kuda Perang Yang Berlari Kencang"},
    101 : {"ar": "Al Qari'ah ", "id": "Hari Kiamat"},
    102 : {"ar": "At Takatsur ", "id": "Bermegah-Megahan"},
    103 : {"ar": "Al 'Ashr ", "id": "Masa"},
    104 : {"ar": "Al Humazah ", "id": "Pengumpat"},
    105 : {"ar": "Al Fiil ", "id": "Gajah"},
    106 : {"ar": "Quraisy ", "id": "Suku Quraisy"},
    107 : {"ar": "Al Ma'un ", "id": "Barang-Barang Yang Berguna"},
    108 : {"ar": "Al Kautsar ", "id": "Nikmat Yang Banyak"},
    109 : {"ar": "Al Kafirun ", "id": "Orang-Orang Kafir"},
    110 : {"ar": "An Nashr ", "id": "Pertolongan"},
    111 : {"ar": "Al Lahab ", "id": "Gejolak Api"},
    112 : {"ar": "Al Ikhlas ", "id": "Memurnikan Keesaan Allah"},
    113 : {"ar": "Al Falaq ", "id": "Waktu Subuh"},
    114 : {"ar": "An Naas ", "id": "Manusia"}
}